import { Inter } from "next/font/google";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/custom.css";
// import "./styles/inter.css";
import "./styles/output.css";

const inter = Inter({
  subsets: ['latin'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Personal Website Adi Julia",
  description: "Generated by Personal Website Adi Julia",
  openGraph: {
    title: "Adi Julia | Portfolio",
    description: "Personal website and data portfolio",
    url: "https://adijulias.my.id",
    images: ["/preview.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
